src/modules/gadget/entities/GadgetFeature.java
package modules.gadget.entities;

import javax.persistence.*;
import javax.validation.constraints.Pattern;

/**
 * Created by gianc on 26/10/2015.
 */
@Entity
@Table(name = "gadget_feature")
@NamedQueries({
        @NamedQuery(name = "GadgetFeature.bucarTodasFeatures",
                query = "select gf " +
                        "from GadgetFeature gf " +
                        "where gf.gadget.id = :gadgetId"),
        @NamedQuery(name = "GadgetFeature.atualiza",
                query = "update GadgetFeature gf " +
                        "set gf.featureName = :newFeatureName, gf.featureDescription =:newFeatureDescription " +
                        "where gf.id = :featureId"),
        @NamedQuery(name = "GadgetFeature.delete",
                    query = "delete from GadgetFeature gf " +
                            "where gf.id = :id" )
})
public class GadgetFeature
{
    private Integer id;

    @Pattern(regexp = "[a-zA-Z áàâãéèêíïóôõöúçñÁÀÂÃÉÈÊÍÏÓÔÕÖÚÇÑ()]{2,50}")
    private String featureName;

    @Pattern(regexp = ".{2,50}")
    private String featureDescription;

    private Gadget gadget;


//------------------------------------------------------------------------------------------------------------
// Construtores

    /**
     * Construtor padrão.
     */
    public GadgetFeature()
    {
    }

//------------------------------------------------------------------------------------------------------------
// Inicio Getters e Setters

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, insertable = true, updatable = true)
    public Integer getId()
    {
        return id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    @Basic
    @Column(name = "feature_name", nullable = false, insertable = true, updatable = true, length = 2147483647)
    public String getFeatureName()
    {
        return featureName;
    }

    public void setFeatureName(String featureName)
    {
        this.featureName = featureName;
    }

    @Basic
    @Column(name = "feature_description", nullable = false, insertable = true, updatable = true, length = 2147483647)
    public String getFeatureDescription()
    {
        return featureDescription;
    }

    public void setFeatureDescription(String featureDescription)
    {
        this.featureDescription = featureDescription;
    }

    // Relacionamentos

    @ManyToOne
    @JoinColumn(name = "gadget_id", referencedColumnName = "id", nullable = false)
    public Gadget getGadget()
    {
        return gadget;
    }

    public void setGadget(Gadget gadget)
    {
        this.gadget = gadget;
    }

// Fim Getters e Setters
//------------------------------------------------------------------------------------------------------------

    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        GadgetFeature that = (GadgetFeature) o;

        if (id != null ? !id.equals(that.id) : that.id != null) return false;
        if (featureName != null ? !featureName.equals(that.featureName) : that.featureName != null)
            return false;
        if (featureDescription != null ? !featureDescription.equals(that.featureDescription) : that.featureDescription != null)
            return false;

        return true;
    }

    @Override
    public int hashCode()
    {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (featureName != null ? featureName.hashCode() : 0);
        result = 31 * result + (featureDescription != null ? featureDescription.hashCode() : 0);
        return result;
    }


}

src/modules/gadget/cdi/GadgetFeatureMB.java
package modules.gadget.cdi;


import modules.gadget.entities.Gadget;
import modules.gadget.entities.GadgetFeature;
import modules.gadget.sessionBeans.GadgetFeatureRepository;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;

@Named
@SessionScoped
public class GadgetFeatureMB implements Serializable
{
    @EJB
    GadgetFeatureRepository gadgetFeatureRepository;

    private Gadget gadget;
    private GadgetFeature gadgetFeature = new GadgetFeature();

    private List<GadgetFeature> gadgetFeatureList;

//------------------------------------------------------------------------------------------------------------
// Construtor

//------------------------------------------------------------------------------------------------------------
// Getters e Setters

    public String getGadgetName()
    {
        if (gadget == null)
            return "Não selecionado";

        return gadget.getName();
    }

    public Gadget getGadget()
    {
        return gadget;
    }

    public void setGadget(Gadget gadget)
    {
        this.gadget = gadget;
    }

    public GadgetFeature getGadgetFeature()
    {
        return gadgetFeature;
    }

    public void setGadgetFeature(GadgetFeature gadgetFeature)
    {
        this.gadgetFeature = gadgetFeature;
    }

    public List<GadgetFeature> getGadgetFeatureList()
    {
        gadgetFeatureList = gadgetFeatureRepository.buscarTodasFeatures(gadget.getId());

        return  gadgetFeatureList;
    }

//------------------------------------------------------------------------------------------------------------
    /**
     * Adiciona uma menssagem ao faces context atual que pode ser exibida usando um growl.
     *
     * @param summary Uma menssagem que será passada ao contexto atual.
     */
    private void addMessage(String summary, FacesMessage.Severity severity, String clientId)
    {
        FacesMessage message = new FacesMessage(severity, summary, null);
        FacesContext.getCurrentInstance().addMessage(clientId, message);
        FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);
    }

    public String cancel()
    {
        addMessage("Operação cancelada pelo usuário.", FacesMessage.SEVERITY_INFO, "1");
        return "listFeature";
    }

//------------------------------------------------------------------------------------------------------------
// Métodos de CRUD

    public String listaFeatures(Gadget gadget)
    {
        this.gadget = gadget;

        return  "listFeature";
    }

    //caso venha a usar bean de request, colocar parametro que recebe um gadget
    public String addFeature()
    {
        gadgetFeature = new GadgetFeature();
        gadgetFeature.setGadget(gadget);

        return  "addFeature?no-redirect";
    }

    public String saveAddFeature()
    {
        gadgetFeatureRepository.insere(gadgetFeature);

        addMessage("Cadastro efetuado com sucesso.", FacesMessage.SEVERITY_INFO, "1");

        return "listFeature?no-redirect";
    }

    public String editFeature(GadgetFeature gadgetFeature)
    {
        this.gadgetFeature = gadgetFeature;

        return "editFeature?no-redirect";
    }

    public String saveFeature()
    {
        gadgetFeatureRepository.atualiza(gadgetFeature);

        addMessage("Edição efetuada com sucesso.", FacesMessage.SEVERITY_INFO, "1");

        return "listFeature?no-redirect";
    }

    public String delete(GadgetFeature gadgetFeature)
    {
        this.gadgetFeature = gadgetFeature;

        gadgetFeatureRepository.deletaDetached(gadgetFeature);

        return null;
    }

}

web/gadget_features/add.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:body>
        <ui:composition template="/templates/main_layout.xhtml">
            <!-- definição do título da aba -->
            <ui:define name="title">#{msgsGadgetFeatures.add_tab_title}</ui:define>

            <ui:define name="content">
                <!-- toda a seção content deve possuir o subcontainer que encapsula tudo -->
                <div class="sub-container">
                    <p:growl id="growl" life="5000"/>
                    <h:form>
                        <p:fieldset legend="#{msgsGadgetFeatures.add_fieldset_title}">
                            <!-- grid responsivo do primefaces -->
                            <div class="ui-grid ui-grid-responsive">
                                <div class="ui-grid-row">
                                    <div class="ui-grid-col-6">
                                        <h:panelGrid columns="3" styleClass="panelgrid-cell-padding-10">
                                            <p:outputLabel value="#{msgsGadgetFeatures.header_feature}"
                                                           for="featureName"/>
                                            <p:inputText id="featureName" required="true"
                                                         value="#{gadgetFeatureMB.gadgetFeature.featureName}"/>
                                            <p:message for="featureName"/>


                                            <p:outputLabel value="#{msgsGadgetFeatures.header_description}"
                                                           for="description"/>
                                            <p:inputText id="description" required="true"
                                                         value="#{gadgetFeatureMB.gadgetFeature.featureDescription}"/>
                                            <p:message for="description"/>
                                        </h:panelGrid>
                                    </div>
                                </div>
                                <div class="ui-grid-row">
                                    <div class="ui-grid-col-6">
                                        <p:commandButton styleClass="submit" ajax="false" value="#{common.save}"
                                                         action="#{gadgetFeatureMB.saveAddFeature()}"/>

                                        <p:commandButton styleClass="submit" ajax="false" immediate="true" value="#{common.cancel}"
                                                         action="#{gadgetFeatureMB.cancel()}"/>
                                    </div>
                                </div>
                            </div>
                        </p:fieldset>
                    </h:form>
                </div>
            </ui:define>

        </ui:composition>
    </h:body>

</html>

web/gadget_features/edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:body>
        <ui:composition template="/templates/main_layout.xhtml">
            <!-- definição do título da aba e das folhas de estilo extras -->
            <ui:define name="title">Editar Feature</ui:define>

            <ui:define name="content">
                <!-- toda a seção content deve possuir o subcontainer que encapsula tudo -->
                <div class="sub-container">
                    <p:growl id="growl" life="5000"/>
                    <h:form>
                        <p:fieldset legend="Editar Feature">
                            <!-- grid responsivo do primefaces -->
                            <div class="ui-grid ui-grid-responsive">
                                <div class="ui-grid-row">
                                    <div class="ui-grid-col-6">
                                        <h:panelGrid columns="3" styleClass="panelgrid-cell-padding-10">
                                            <p:outputLabel value="#{msgsGadgetFeatures.header_feature}"
                                                           for="featureName"/>
                                            <p:inputText id="featureName" required="true"
                                                         value="#{gadgetFeatureMB.gadgetFeature.featureName}"/>
                                            <p:message for="featureName"/>

                                            <p:outputLabel value="#{msgsGadgetFeatures.header_description}"
                                                           for="description"/>
                                            <p:inputText id="description" required="true"
                                                         value="#{gadgetFeatureMB.gadgetFeature.featureDescription}"/>
                                            <p:message for="description"/>
                                        </h:panelGrid>
                                    </div>
                                </div>
                                <div class="ui-grid-row">
                                    <div class="ui-grid-col-6">
                                        <p:commandButton ajax="false" value="#{common.save}" styleClass="submit"
                                                         action="#{gadgetFeatureMB.saveFeature()}"/>
                                        <p:commandButton ajax="false" value="#{common.cancel}" styleClass="submit"
                                                         action="#{gadgetFeatureMB.cancel()}" immediate="true"/>
                                    </div>
                                </div>
                            </div>
                        </p:fieldset>
                    </h:form>
                </div>
            </ui:define>

        </ui:composition>
    </h:body>

</html>

web/gadget_features/list.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:body>
        <ui:composition template="/templates/main_layout.xhtml">
            <!-- definição do título da aba e das folhas de estilo extras -->
            <ui:define name="title">#{msgsGadgetFeatures.list_tab_title}</ui:define>

            <ui:define name="content">
                <!-- toda a seção content deve possuir o subcontainer que encapsula tudo -->
                <div class="sub-container">
                    <p:growl id="growl" life="5000"/>
                    <h:form>
                        <p:fieldset legend="Gadget: #{gadgetFeatureMB.gadgetName}">
                            <!--adicionar uma feature-->
                            <p:commandButton ajax="false" value="#{common.add}"
                                             action="#{gadgetFeatureMB.addFeature()}"/>

                            <!--retornar a lista de gadgets-->
                            <p:commandButton ajax="false" value="#{common.back}" action="gadgetList"/>

                            <p:dataTable value="#{gadgetFeatureMB.gadgetFeatureList}" var="feature">
                                <!--id-->
                                <p:column width="10%">
                                    <f:facet name="header">Id</f:facet>
                                    <h:outputText value="#{feature.id}"/>
                                </p:column>

                                <!--nome-->
                                <p:column>
                                    <f:facet name="header">Feature</f:facet>
                                    <h:outputText value="#{feature.featureName}"/>
                                </p:column>

                                <!--descricao-->
                                <p:column>
                                    <f:facet name="header">Descricao</f:facet>
                                    <h:outputText value="#{feature.featureDescription}"/>
                                </p:column>

                                <!--ação-->
                                <p:column>
                                    <f:facet name="header">Ações</f:facet>

                                    <p:commandButton ajax="false" value="#{common.edit}"
                                                     action="#{gadgetFeatureMB.editFeature(feature)}"/>
                                    <p:commandButton ajax="false" value="Delete"
                                                     action="#{gadgetFeatureMB.delete(feature)}"/>

                                </p:column>
                            </p:dataTable>
                        </p:fieldset>
                    </h:form>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>